production:
  entity: \Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSetting
  fields: 
    user:
      title: ngettext('User', 'Users', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\User\User
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            User.name: asc
      default: true
    residentialDevice:
      title: ngettext('Residential Device', 'Residential Devices', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDevice
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            ResidentialDevice.name: asc
      default: true
    cfwToretailAccount:
      title:  ngettext('Retail Account', 'Retail Accounts', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\RetailAccount\RetailAccount
          filterClass: IvozProvider_Klear_Filter_RetailAccounts
          fieldName:
            fields:
            - name
            template: '%name%'
          order:
            RetailAccount.name: asc
        'null': _("Unassigned")
    callTypeFilter:
      title: _('Call type')
      type: select
      required: true
      source:
        data: inline
        values:
          'internal': _('Internal')
          'external': _('External')
          'both': _('Both')
    callForwardType:
      title: _('Call forward type')
      type: select
      required: true
      source:
        data: inline
        filterClass: IvozProvider_Klear_Filter_CallForwardTypes
        values:
          'inconditional':
            title: _('Inconditional')
            visualFilter:
              hide: [ noAnswerTimeout ]
          'noAnswer':
            title: _('No Answer')
            visualFilter:
              show: [ noAnswerTimeout ]
          'busy':
            title: _('Busy')
            visualFilter:
              hide: [ noAnswerTimeout]
          'userNotRegistered':
            title: _('Unreachable')
            visualFilter:
              hide: [ noAnswerTimeout ]
    targetType:
      title: _('Target type')
      type: select
      required: false
      source:
        data: inline
        filterClass: IvozProvider_Klear_Filter_TargetTypes
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              show: [ ]
              hide: [ extension, voiceMailUser, numberCountry, numberValue, cfwToretailAccount ]
          'number':
            title: _('Number')
            visualFilter:
              show: [ numberCountry, numberValue ]
              hide: [ extension, voiceMailUser, cfwToretailAccount ]
          'extension':
            title: ngettext('Extension', 'Extensions', 1)
            visualFilter:
              show: [ extension ]
              hide: [ numberCountry, numberValue, voiceMailUser, cfwToretailAccount ]
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: [ voiceMailUser ]
              hide: [ extension, numberCountry, numberValue, cfwToretailAccount ]
          'retail':
            title: ngettext('Retail Account', 'Retail Accounts', 1)
            visualFilter:
              show: [ cfwToretailAccount ]
              hide: [ extension, numberCountry, numberValue, voiceMailUser ]
    numberCountry:
      title: _('Country')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    numberValue:
      title: _('Number')
      pattern: "^[0-9]+$"
      type: text
      trim: both
      required: true
    extension:
      title: ngettext('Extension', 'Extensions', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Extension\Extension
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields: 
              - number
            template: '%number%'
          order:
            Extension.number: asc
        'null': _("Unassigned")
    voiceMailUser:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\User\User
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName: 
            fields: 
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    noAnswerTimeout:
      title: _('No answer timeout')
      type: number
      defaultValue: 10
      required: true
      source:
        control: Spinner
    targetTypeValue:
      title: _('Target type value')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_RouteTarget
        method: getCallForwardTarget
    enabled:
      title: _('Enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
